export const metadata = {
  title: 'Pomodoro Timer',
  description: 'Generated by PPOON 🍳',
  icon:{
    icon: ['/favicon.ico'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png'],
  }
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
